// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';
import {config} from '../models';

export function CancelQuery():Promise<void>;

export function ClearHistory():Promise<db.SimpleResult>;

export function Connect(arg1:db.ConnectionParams):Promise<db.ConnectResult>;

export function DeleteSavedConnection(arg1:string):Promise<db.SimpleResult>;

export function Disconnect():Promise<db.SimpleResult>;

export function ExecuteQuery(arg1:string):Promise<db.QueryExecutionResult>;

export function ExportResult(arg1:string,arg2:string):Promise<main.FileSaveResult>;

export function GetConnectionStatus():Promise<db.ConnectionStatus>;

export function GetHistory():Promise<Array<config.HistoryRecord>>;

export function GetSavedConnections():Promise<config.SavedConnectionsResult>;

export function GetSavedPassword(arg1:string):Promise<string>;

export function OpenFile():Promise<main.FileResult>;

export function SaveConnection(arg1:config.SavedConnection):Promise<db.SimpleResult>;

export function SaveConnectionWithPassword(arg1:config.SavedConnection,arg2:string):Promise<db.SimpleResult>;

export function SaveFile(arg1:string,arg2:string):Promise<main.FileSaveResult>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.FileSaveResult>;

export function SaveHistory(arg1:config.HistoryRecord):Promise<db.SimpleResult>;

export function TestConnection(arg1:db.ConnectionParams):Promise<db.TestConnectionResult>;
