// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery() {
  return window['go']['main']['App']['CancelQuery']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExportResult(arg1, arg2) {
  return window['go']['main']['App']['ExportResult'](arg1, arg2);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSavedPassword(arg1) {
  return window['go']['main']['App']['GetSavedPassword'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveConnectionWithPassword(arg1, arg2) {
  return window['go']['main']['App']['SaveConnectionWithPassword'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
